export const SET_TOP_PANEL = 'SET_TOP_PANEL';
export const SET_THEME = 'SET_THEME';
export const SET_MY_ORDERS = 'SET_MY_ORDERS';
export const SET_ORDER_CLOSE_MODAL = 'SET_ORDER_CLOSE_MODAL';
export const OPEN_PAGE = 'OPEN_PAGE';
export const CLOSE_PAGE = 'CLOSE_PAGE';
export const SWITCH_NOTIFICATION = 'SWITCH_NOTIFICATION';